project_news_board/account/urls.py
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include
from .views import *

app_name = 'account'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('confirm/<int:code_id>/', confirm, name='confirm'),
    path('reset', reset, name='reset'),
]

project_news_board/desk/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'desk'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('desk/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('desk/create/', PostCreateView.as_view(), name='post_create'),
    path('desk/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('desk/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('desk/<int:pk>/reply/', reply, name='reply'),
    path('desk/<int:pk>/replied/', replied, name='replied'),
    path('private/', PrivateOfficeView.as_view(), name='private_office'),
    path('private/<int:pk>/', ReplyDetailView.as_view(), name='reply_detail'),
    path('private/<int:pk>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('private/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('private/by_post/<int:post_id>/', SortedByPostView.as_view(), name='sorted_by_post'),
    path('subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/', unsubscribe, name='unsubscribe'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_news_board/project_news_board/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url

from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
#    path('desk/', include('desk.urls', namespace='desk')),
    path('', include('desk.urls', namespace='desk')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

]

project_news_board/account/models.py
from django.contrib.auth.models import User
from django.db import models


class Code(models.Model):
    code = models.IntegerField()
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

project_news_board/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class ConfirmationForm(forms.Form):
    name = forms.CharField(max_length=128)
    code = forms.IntegerField(min_value=10000, max_value=99999)

project_news_board/account/views.py
import random
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from .forms import SignUpForm, ConfirmationForm
from .models import Code


def signup(request):
    # First step of registration including secret code generation (generated_code) and
    # temporary user creation (usr with is_active=False flag). Sending mail to usr
    # with that code and redirecting to next page with comparison form. Filling context
    # with generated_code to bring it through to the next view function. Redirecting to
    # 'reset' page in a case of validation problem (repeating usr object in db) which deletes
    # all user objects with is_active=False flag.
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            usr = User.objects.create_user(username=request.POST['username'], email=request.POST['email'],
                                           password=request.POST['password1'], is_active=False)
            generated_code = Code.objects.create(name=User.objects.get(id=usr.id), code=random.randint(10000, 99999))
            print(generated_code.code)
            send_mail(subject='Подтверждение регистрации.',
                      message=f'Отправьте следующий код {generated_code.code} для подтверждения регистрации.',
                      from_email=None,
                      recipient_list=[request.POST['email']])
            context = {
                'generated_code': generated_code,
                'usr': usr
            }
            return render(request, 'registration/confirm.html', context)
        else:
            return render(request, 'registration/reset.html')
    else:
        form = SignUpForm()
        return render(request, 'registration/signup.html', {'form': form})


def confirm(request, code_id):
    # Second step of registration including comparison of usr_code and generated code (confirmation.code).
    # If succeeded we get is_active=True flag for user object in db.
    if request.method == 'POST':
        form = ConfirmationForm(request.POST)
        if form.is_valid():
            usr = request.POST['name']
            usr_code = request.POST['code']
            confirmation = Code.objects.get(id=code_id)
            if int(usr_code) == int(confirmation.code):
                usr_upd = User.objects.get(username=confirmation.name)
                usr_upd.is_active = True
                usr_upd.save()
                return render(request, 'templates/registration/successful.html', {'usr': usr})
            return render(request, 'templates/registration/unsuccessful.html')
        return render(request, 'templates/registration/unsuccessful.html')
    else:
        form = ConfirmationForm()
        return render(request, 'templates/registration/confirm.html', {'form': form})


def reset(request):
    obj = User.objects.filter(is_active=False)
    obj.delete()
    return redirect('desk:index')

project_news_board/account/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock %}</title>

        {% load static %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'desk/css/blog.css' %}" rel="stylesheet" />
    </head>
    <body>
       {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Доска объявлений</a>
                <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler"
                        data-target="#navbarResponsive" data-toggle="collapse"
                        type="button">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ml-auto">
               {% if not user.is_authenticated %}
               <li class="nav-item active">
                   <a class="nav-link" href="{% url 'desk:index' %}">Главная</a>
               </li>
               <li class="nav-item registr">
                   <a class="nav-link" href="{% url 'account:signup' %}">Регистрация</a>
               </li>
               <li class="nav-item registr">
                   <a class="nav-link" href="{% url 'login' %}">Вход</a>
               </li>
               {% endif %}
               <li class="nav-link px-5">Вы вошли как: {{ user.username }}  <a href="{% url 'logout' %}">Выйти</a></li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'desk:private_office' %}">Профиль</a>
              </li>


       </div>
   </div>
</nav>
       {% endblock nav %}

       <div class="container">
           <div class="col-lg-12 text-center">
               {% block content %} {% endblock content %}
           </div>
       </div>

    </body>
</html>