project_news_board/account/urls.py
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include
from .views import *

app_name = 'account'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('confirm/<int:code_id>/', confirm, name='confirm'),
    path('reset', reset, name='reset'),
]

project_news_board/desk/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'desk'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('desk/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('desk/create/', PostCreateView.as_view(), name='post_create'),
    path('desk/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('desk/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('desk/<int:pk>/reply/', reply, name='reply'),
    path('desk/<int:pk>/replied/', replied, name='replied'),
    path('private/', PrivateOfficeView.as_view(), name='private_office'),
    path('private/<int:pk>/', ReplyDetailView.as_view(), name='reply_detail'),
    path('private/<int:pk>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('private/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('private/by_post/<int:post_id>/', SortedByPostView.as_view(), name='sorted_by_post'),
    path('subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/', unsubscribe, name='unsubscribe'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_news_board/project_news_board/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url

from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
#    path('desk/', include('desk.urls', namespace='desk')),
    path('', include('desk.urls', namespace='desk')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

]

project_news_board/desk/models.py
from django.db import models
from django.contrib.auth.models import User



class Author(models.Model):
    name = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    is_subscriber = models.BooleanField(
        verbose_name='Подписчик',
        default=False
    )

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return f'{self.name.username}'


class Post(models.Model):
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    title = models.CharField(
        max_length=128,
        verbose_name='Заголовок'
    )
    content = models.TextField(
        verbose_name='Объявление'
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='Категория'
    )
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True, blank=True)
    video = models.FileField(upload_to='video/', null=True, blank=True)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return f'posts/{self.pk}'


class Category(models.Model):
    categories = [('tank', 'Танки'),
                  ('healer', 'Хилы'),
                  ('dd', 'ДД'),
                  ('trader', 'Торговцы'),
                  ('master', 'Гилдмастеры'),
                  ('quest', 'Квестгиверы'),
                  ('smith', 'Кузнецы'),
                  ('skinner', 'Кожевники'),
                  ('potion', 'Зельевары'),
                  ('caster', 'Мастера заклинаний'),
                  ]

    name = models.CharField(
        max_length=8,
        choices=categories,
        verbose_name='Категория',
        default='tank',
        unique=True
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.get_name_display()


class Reply(models.Model):
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        verbose_name='Объявление'
    )
    content = models.TextField(verbose_name='Отклик')
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return f'{self.content[0:32]}'


class UserProfile(models.Model):
    user = models.OneToOneField(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

project_news_board/desk/forms.py
from django import forms
from .models import Reply, Post
from django.contrib.auth.forms import AuthenticationForm
from django import forms



class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']

    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), label='Содержимое')

#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'content', 'category']


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'image', 'video']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Заголовок поста'
            }),

            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст поста'
            }),

            'image': forms.FileInput
        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': "inputPassword"}))

project_news_board/desk/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .forms import ReplyForm, PostForm, LoginUserForm
from .models import Post, Reply, Author, Category


class IndexView(ListView):
    model = Post
    ordering = '-created'
    template_name = 'desk/post/list.html'
    context_object_name = 'posts'
    paginate_by = 5


class PostDetailView(DetailView):
    model = Post
    ordering = '-created'
    template_name = 'desk/post/detail.html'
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    success_url = ''
    form_class = PostForm
    template_name = 'desk/post/create.html'
    context = {

    }

    def post(self, request, *args, **kwargs):
        obj = Post(
            title=request.POST['title'],
            content=request.POST['content'],
            category=Category.objects.get(id=request.POST['category']),
            author=Author.objects.get(name=request.user)
        )
        obj.save()
        return redirect('desk:index')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    success_url = reverse_lazy('desk:index')
    fields = ['title', 'content', 'category', 'image']
    template_name = 'desk/post_update.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('desk:index')
    template_name = 'desk/post/delete.html'


# Not the best fulfillment ...
@login_required
def reply(request, pk):
    author, status = Author.objects.get_or_create(name=request.user)
    post = Post.objects.get(id=pk)
    form = ReplyForm()
    context = {'post': post,
               'form': form,
               'author': author
               }
    return render(request, 'desk/reply.html', context)


def replied(request, pk):
    content = request.POST['content']
    author = Author.objects.get(name=request.user)
    post = Post.objects.get(id=pk)
    Reply.objects.create(author=author, post=post, content=content)
    return redirect('desk:index')


class PrivateOfficeView(LoginRequiredMixin, ListView):
    model = Reply
    template_name = 'desk/private_office.html'
    context_object_name = 'replies'

    def get_queryset(self):
        author, status = Author.objects.get_or_create(name=self.request.user)
        queryset = Reply.objects.filter(post__author=author).order_by('-created')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['current_user'] = Author.objects.get(name=self.request.user)
        return context


class SortedByPostView(ListView):
    model = Reply
    template_name = 'desk/replies_by_post.html'
    ordering = '-created'
    context_object_name = 'replies'

    def get_queryset(self):
        queryset = Reply.objects.filter(post=Post.objects.get(id=self.kwargs['post_id']))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['this_post'] = Post.objects.get(id=self.kwargs['post_id'])
        return context


class ReplyDetailView(DetailView):
    model = Reply
    ordering = '-created'
    template_name = 'desk/reply_detail.html'
    context_object_name = 'reply'


class ReplyDeleteView(DeleteView):
    model = Reply
    success_url = reverse_lazy('desk:private_office')
    template_name = 'desk/reply_delete.html'


def reply_approve(request, pk):
    obj = Reply.objects.get(id=pk)
    obj.approved = True
    obj.save()
    return redirect('/private')


@login_required
def subscribe(request):
    obj = Author.objects.get(name=request.user)
    obj.is_subscriber = True
    obj.save()
    return redirect('/private')


@login_required
def unsubscribe(request):
    obj = Author.objects.get(name=request.user)
    obj.is_subscriber = False
    obj.save()
    return redirect('/private')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'desk/users/login.html'


@login_required
def profile(request):
    user_posts = Author.objects.filter(name=request.user)
    context = {
        'posts': user_posts,
    }
    return render(request, 'desk/users/profile.html', context)

def logout_user(request):
    logout(request)
    return redirect('desk:index')

project_news_board/desk/templates/desk/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock %}</title>

        {% load static %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <!-- Core theme CSS (includes Bootstrap)-->
    </head>
    <body>
       {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Доска объявлений</a>
                <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler"
                        data-target="#navbarResponsive" data-toggle="collapse"
                        type="button">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ml-auto">
               {% if not user.is_authenticated %}
               <li class="nav-item active">
                   <a class="nav-link" href="{% url 'desk:index' %}">Главная</a>
               </li>
               <li class="nav-item registr">
                   <a class="nav-link" href="{% url 'account:signup' %}">Регистрация</a>
               </li>
               <li class="nav-item registr">
                   <a class="nav-link" href="{% url 'login' %}">Вход</a>
               </li>
               {% endif %}
               {% if user.is_authenticated %}
               <li class="nav-link px-5">Вы вошли как: {{ user.username }}  <a href="{% url 'desk:logout' %}">Выйти</a></li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'desk:private_office' %}">Профиль</a>
              </li>
               <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'desk:post_create'%}">Создать объявление</a></li>
               {% endif %}


       </div>
   </div>
</nav>
       {% endblock nav %}

       <div class="container">
           <div class="col-lg-12 text-center">
               {% block content %} {% endblock content %}
           </div>
       </div>

    </body>
</html>

project_news_board/desk/templates/desk/confirm.html
{% extends 'default.html' %}
{% block title %}Подтверждение регистрации{% endblock title %}
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Главная</a>
        </div>
    </nav>
{% endblock nav %}
{% block content %}
<body>
    <div class="container">
    <form method="post" action="{% url 'desk:confirm' generated_code.id %}">
        {% csrf_token %}
        <p>{{ usr.username }}, введите код подтверждения</p>
        {{form.as_p}}
        <input id="usr_name" type="hidden" name="name" value="{{ usr.username }}">
        <label for="usr_code">Введите код: </label>
        <input id="usr_code" type="text" name="code" placeholder="Ваш код" value="{{ code }}">
        <p><input type="submit" value="Проверка"></p>
    </form>
    </div>
</body>
{% endblock content %}

project_news_board/desk/templates/desk/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
</head>
<body>
    <form method="post" action="{% url 'account:login' %}">
    {% csrf_token %}
    <table>{{form.as_table}}</table>
    <p><input type="submit" value="Вход"></p>
    <input type="hidden" name="next" value="{{ next }}">
    </form>
</body>
</html>

project_news_board/desk/templates/desk/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
    {% endif %}
    <span class="current">Страница {{ page.number }} из {{ page.paginator.num_pages }}.</span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Следующая</a>
    {% endif %}
    </span>
    </div>
   

project_news_board/desk/templates/desk/post_update.html
{% extends 'base.html' %}
{% block title %}Изменение объявления{% endblock title %}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="p-sm-1">Изменение объявления № {{post.id}}</h1>
        <h3 class="p-sm-1">от автора: {{user}}</h3>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.image }}
            {{ form.video }}
        <input type="submit" value="Изменить"/>
        </form>
    </div>
{% endblock content %}

project_news_board/desk/templates/desk/private_office.html
{% extends 'desk/base.html' %}
{% load cache %}
{% block title %}Личный кабинет{% endblock title %}
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Главная</a>
            {% if not user.username %}
            <a class="nav-link active" href="{% url 'account:signup' %}">Регистрация</a>
            <a class="nav-link active" href="{% url 'account:login' %}">Вход</a>
            {% else %}

            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <a class="nav-link active" href="{% url 'desk:logout' %}">Выход</a>
                    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'desk:post_create'%}">Создать объявление</a></li>

                    {% endif %}
                    {% if not current_user.is_subscriber %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'desk:subscribe' %}">Подписаться на рассылку</a></li>
                    {% else%}
                    <li class="nav-item"><a class="nav-link" href="{% url 'desk:unsubscribe' %}">Отписаться от рассылки</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">Текущий пользователь: {{user.username}}</div>
    <div class="container">Подписка оформлена: {{current_user.is_subscriber|yesno:"Да, Нет, -"}}</div>
{% endblock nav %}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="p-sm-3">Отклики на объявления</h1>
        <hr>
        <div class="container text-center mt-5">
        <table class="container">
            <tr>
                <td><h5 class="p-sm-3">Отклики</h5></td>
                <td><h5 class="p-sm-3">Автор</h5></td>
                <td><h5 class="p-sm-3">Дата создания</h5></td>
                <td><h5 class="p-sm-3">Для объявления</h5></td>
                <td><h5 class="p-sm-3">Одобрен</h5></td>
            </tr>
            {% for item in replies %}
            <tr>
                <td><h5 class="p-sm-3"><a href="{% url 'desk:reply_detail' item.id %}">{{item.content|truncatewords:4}}</a></h5></td>
                <td><h5 class="p-sm-3">{{item.author}}</h5></td>
                <td><h5 class="p-sm-3">{{item.created}}</h5></td>
                <td><h5 class="p-sm-3"><a href="{% url 'desk:sorted_by_post' post_id=item.post.id %}">{{item.post}}</a></h5></td>
                <td><h5 class="p-sm-3">{{item.approved|yesno:"Да, Нет, -"}}</h5></td>
            </tr>
            {% endfor %}
        </table>
        </div>
    </div>
{% endblock content %}

project_news_board/desk/templates/desk/reply.html
{% extends 'base.html' %}
{% block title %}Отклик{% endblock title %}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="p-sm-1">Отклик на объявление № {{post.pk}} --></h1>
        <h3 class="p-sm-1">"{{post.title}}" автора: {{post.author}}</h3>
        <hr>
        <h5 class="p-sm-1">От пользователя {{author.name}}</h5>
        <hr>
        <form action="{% url 'desk:replied' post.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Создать"/>
        </form>
    </div>
{% endblock content %}

project_news_board/desk/templates/desk/reply_delete.html
{% extends 'base.html' %}
{% block title %}Удаление отклика{% endblock title %}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="p-sm-1">Удаление отклика "{{object|truncatewords:3}}" </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
        <input type="submit" value="Удалить!"/>
        </form>
    </div>
{% endblock content %}

project_news_board/desk/templates/desk/reply_detail.html
{% extends 'base.html' %}
{% block title %}Подробно{% endblock title %}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="p-sm-3">Отклик № {{reply.pk}}</h1>
        <p class="p-sm-1">к объявлению "{{reply.post}}"</p>
        <hr>
        <a class="navbar-toggler" href="{% url 'desk:reply_delete' reply.pk %}">Удалить отклик</a>
        {% if not reply.approved%}
            <a class="navbar-toggler" href="{% url 'desk:reply_approve' reply.pk %}">Принять отклик</a>
        {% endif %}
        <hr>
        <h4 class="p-sm-3">Автор {{reply.author}}</h4>
        <h5 class="p-sm-3">Создано {{reply.created}}</h5>
        <p class="p-sm-1">{{reply.content}}</p>
    </div>
{% endblock content %}

project_news_board/desk/templates/desk/reset.html
{% extends 'base.html' %}
{% block title %}Сброс процесса регистрации{% endblock title %}
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Главная</a>
        </div>
    </nav>
{% endblock nav %}
{% block content %}
<body>
    <div class="container">
    <form method="post" action="{% url 'account:reset' %}">
        {% csrf_token %}
        <p>Произошел сбой при регистрации. Возможно пользователь с таким именем уже существует.
            Если Вы неудачно вводили код при сверке регистрации, рекомендуем сбросить прогресс...</p>
        <p><input type="submit" value="Сброс"></p>
    </form>
    </div>
</body>
{% endblock content %}

project_news_board/desk/templates/desk/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <form method="post" action="{% url 'account:signup' %}">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    {{form.as_p}}
    <p><input type="submit" value="Регистрация"></p>
    </form>
</body>
</html>

project_news_board/desk/templates/desk/successful.html
{% extends 'base.html' %}
{% block title %}Успешная регистрация{% endblock title %}
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Главная</a>
        </div>
    </nav>
{% endblock nav %}
{% block content %}
<div class="container">
    <h3>Уважаемый {{usr}}, регистрация прошла успешно!</h3>
</div>
{% endblock content %}

project_news_board/desk/templates/desk/unsuccessful.html
{% extends 'base.html' %}
{% block title %}Неверный код{% endblock title %}
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'desk:index' %}">Главная</a>
        </div>
    </nav>
{% endblock nav %}
{% block content %}
<h3>Неверный код, повторите ввод!</h3>
{% endblock content %}