project_news_board/desk/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *


app_name = 'desk'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('desk/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('desk/create/', PostCreateView.as_view(), name='post_create'),
    path('desk/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('desk/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('desk/<int:pk>/reply/', reply, name='reply'),
    path('desk/<int:pk>/replied/', replied, name='replied'),
    path('private/', PrivateOfficeView.as_view(), name='private_office'),
    path('private/<int:pk>/', ReplyDetailView.as_view(), name='reply_detail'),
    path('private/<int:pk>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('private/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('private/by_post/<int:post_id>/', SortedByPostView.as_view(), name='sorted_by_post'),
    path('subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/', unsubscribe, name='unsubscribe'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_news_board/project_news_board/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url

from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
#    path('desk/', include('desk.urls', namespace='desk')),
    path('', include('desk.urls', namespace='desk')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

]

project_news_board/desk/models.py
from django.db import models
from django.contrib.auth.models import User



class Author(models.Model):
    name = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    is_subscriber = models.BooleanField(
        verbose_name='Подписчик',
        default=False
    )

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return f'{self.name.username}'


class Post(models.Model):
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    title = models.CharField(
        max_length=128,
        verbose_name='Заголовок'
    )
    content = models.TextField(
        verbose_name='Объявление'
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='Категория'
    )
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True, blank=True)
    video = models.FileField(upload_to='video/', null=True, blank=True)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return f'posts/{self.pk}'


class Category(models.Model):
    categories = [('tank', 'Танки'),
                  ('healer', 'Хилы'),
                  ('dd', 'ДД'),
                  ('trader', 'Торговцы'),
                  ('master', 'Гилдмастеры'),
                  ('quest', 'Квестгиверы'),
                  ('smith', 'Кузнецы'),
                  ('skinner', 'Кожевники'),
                  ('potion', 'Зельевары'),
                  ('caster', 'Мастера заклинаний'),
                  ]

    name = models.CharField(
        max_length=8,
        choices=categories,
        verbose_name='Категория',
        default='tank',
        unique=True
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.get_name_display()


class Reply(models.Model):
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        verbose_name='Объявление'
    )
    content = models.TextField(verbose_name='Отклик')
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return f'{self.content[0:32]}'


class UserProfile(models.Model):
    user = models.OneToOneField(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

project_news_board/desk/forms.py
from django import forms
from .models import Reply, Post
from django.contrib.auth.forms import AuthenticationForm
from django import forms



class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']

    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), label='Содержимое')

#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'content', 'category']


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'image', 'video']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Заголовок поста'
            }),

            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст поста'
            }),

            'image': forms.FileInput
        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': "inputPassword"}))

project_news_board/desk/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .forms import ReplyForm, PostForm, LoginUserForm
from .models import Post, Reply, Author, Category


class IndexView(ListView):
    model = Post
    ordering = '-created'
    template_name = 'desk/post/list.html'
    context_object_name = 'posts'
    paginate_by = 5


class PostDetailView(DetailView):
    model = Post
    ordering = '-created'
    template_name = 'desk/post/detail.html'
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    success_url = ''
    form_class = PostForm
    template_name = 'desk/post/create.html'
    context = {

    }

    def post(self, request, *args, **kwargs):
        obj = Post(
            title=request.POST['title'],
            content=request.POST['content'],
            category=Category.objects.get(id=request.POST['category']),
            author=Author.objects.get(name=request.user)
        )
        obj.save()
        return redirect('desk:index')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    success_url = reverse_lazy('desk:index')
    fields = ['title', 'content', 'category', 'image']
    template_name = 'desk/post_update.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('desk:index')
    template_name = 'desk/post/delete.html'


# Not the best fulfillment ...
@login_required
def reply(request, pk):
    author, status = Author.objects.get_or_create(name=request.user)
    post = Post.objects.get(id=pk)
    form = ReplyForm()
    context = {'post': post,
               'form': form,
               'author': author
               }
    return render(request, 'desk/reply.html', context)


def replied(request, pk):
    content = request.POST['content']
    author = Author.objects.get(name=request.user)
    post = Post.objects.get(id=pk)
    Reply.objects.create(author=author, post=post, content=content)
    return redirect('desk:index')


class PrivateOfficeView(LoginRequiredMixin, ListView):
    model = Reply
    template_name = 'desk/private_office.html'
    context_object_name = 'replies'

    def get_queryset(self):
        author, status = Author.objects.get_or_create(name=self.request.user)
        queryset = Reply.objects.filter(post__author=author).order_by('-created')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['current_user'] = Author.objects.get(name=self.request.user)
        return context


class SortedByPostView(ListView):
    model = Reply
    template_name = 'desk/replies_by_post.html'
    ordering = '-created'
    context_object_name = 'replies'

    def get_queryset(self):
        queryset = Reply.objects.filter(post=Post.objects.get(id=self.kwargs['post_id']))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['this_post'] = Post.objects.get(id=self.kwargs['post_id'])
        return context


class ReplyDetailView(DetailView):
    model = Reply
    ordering = '-created'
    template_name = 'desk/reply_detail.html'
    context_object_name = 'reply'


class ReplyDeleteView(DeleteView):
    model = Reply
    success_url = reverse_lazy('desk:private_office')
    template_name = 'desk/reply_delete.html'


def reply_approve(request, pk):
    obj = Reply.objects.get(id=pk)
    obj.approved = True
    obj.save()
    return redirect('/private')


@login_required
def subscribe(request):
    obj = Author.objects.get(name=request.user)
    obj.is_subscriber = True
    obj.save()
    return redirect('/private')


@login_required
def unsubscribe(request):
    obj = Author.objects.get(name=request.user)
    obj.is_subscriber = False
    obj.save()
    return redirect('/private')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'desk/users/login.html'


@login_required
def profile(request):
    user_posts = Author.objects.filter(name=request.user)
    context = {
        'posts': user_posts,
    }
    return render(request, 'desk/users/profile.html', context)

def logout_user(request):
    logout(request)
    return redirect('desk:index')

project_news_board/desk/templates/desk/post/comment.html
{% extends "desk/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
 {% if comment %}
 <h2>Your comment has been added.</h2>
 <p><a href="{% url 'desk:post_detail' post.id %}">Back to the post</a></p>
 {% else %}
 {% include "desk/post/includes/comment_form.html" %}
{% endif %}
{% endblock %}

project_news_board/desk/templates/desk/post/create.html
{% extends 'desk/base.html' %}
{% block title %}Добавление поста{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h1>Форма добавления</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
        {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить пост</button>
            <span>{{ error }}</span>
    {% else %}
        Пройдите регистрацию или войдите под своей учетной записью
    {% endif %}
  </form>
{% endblock %}

project_news_board/desk/templates/desk/post/delete.html
{% extends 'desk/base.html' %}
{% block title %}Удаление поста{% endblock %}
{% block content %}
  <h1>Удаление новости</h1>
  <form method="post">
    {% csrf_token %}
    <h2>{{ object.title }}</h2>
    <p>{{ object.body }}</p>
    <button class="btn btn-success" type="submit">Удалить пост</button>
    <span>{{ error }}</span>
  </form>
{% endblock %}

project_news_board/desk/templates/desk/post/detail.html
{% extends "desk/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date"> Опубликовано {{ post.publish }}  {{ post.author }} <strong>Категория {{ post.category }}</strong></p>
    {{ post.body|linebreaks }}
     <p>{{post.content|safe}}</p>

        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" width="800" height="600">
        {% endif %}

        {% if post.video %}
            <video width="800" height="600" controls>
            <source src="{{ post.video.url }}" type="video/mp4">
            Your browser does not support the video tag.
            </video>
        {% endif %}

   <hr>
        {% if post.author.name.username != user.username %}
            <a class="navbar-toggler" href="{% url 'desk:reply' post.pk %}">Оставить отклик</a>
        {% else %}
            <a class="navbar-toggler" href="{% url 'desk:post_update' post.pk %}">Изменить свое объявление</a>
            <a class="navbar-toggler" href="{% url 'desk:post_delete' post.pk %}">Удалить свое объявление</a>
        {% endif %}
        {% if user.is_authenticated and request.user.username == post.author.username %}
        <a href="{% url 'desk:post_delete' post.id %}" class="btn btn-danger">Удалить пост</a>
        <a href="{% url 'desk:post_update' post.id %}" class="btn btn-primary">Редактировать</a>
        {% endif %}    
    <div>
    </div>
    
    
    
{% endblock %}

project_news_board/desk/templates/desk/post/edit_page.html
{% extends 'desk/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

{% endblock content %}

project_news_board/desk/templates/desk/post/list.html
{% extends "desk/base.html" %}
{% block title %}Доска объявлений{% endblock %}
{% block content %}
<hr>
    <h1>Объявления</h1>
<hr>
        {% for post in posts %}
        <h2 class="mt-20">
            <a class="alert alert-dark pt-2 mb-1 lh-2" href="{% url 'desk:post_detail' post.id %}">{{ post.title }}</a>

        </h2>
        <br>
        {% if post.image %}
            <img src="{{ post.image.url }}"  width="400" height="300">
        {% endif %}
        <p class="date mt-5"> Опубликовано {{ post.publish }}  {{ post.author }} <strong>Кaтегория {{ post.category }}</strong></p>
 
        <hr>
        {% endfor %}
        {% include 'desk/pagination.html' with page=page_obj %}
{% endblock %}

project_news_board/desk/templates/desk/post/share.html
{% extends "desk/base.html" %}

{% block title %}Поделиться постом{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail отправлен</h1>
        <p>
        "{{ post.title }}" E-mail успешно отправлен {{ form.cleaned_data.to }}.
        </p>
        {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}